### ISSUE TITLE
Issue while downloading the chart by passing the full URL.

### ISSUE THREAD

**Issue by raj-shekhar1** [deliverybot/helm#21]
@colinjfw still same issue with helmv2 
the git hub action is not able to download the chart. the error below - Error: failed to download "xxxx" (hint: running helm repo update may help)
##[error]Error: The process 'helm' failed with exit code 1
##[error]The process 'helm' failed with exit code 1
##[error]Docker run failed with exit code 1
Related - https://github.com/deliverybot/helm/issues/11

**Comment by colinjfw** [comment]
Thanks! We can definitely add a `helm repo update` command into the process. Do you want to contribute a fix?

Probably would need to do this at this line: https://github.com/deliverybot/helm/blob/master/index.js#L236

**Comment by raj-shekhar1** [comment]
Hi Col,
I tried adding the ```repo add ``` , it is working fine but still issue with helm upgrade for helmv2.
The below command works locally but not with github action - 
COMMAND -
``` helm upgrade validator6 charts***ose.com/aonity ***install ***atomic ***namespace=valid6 ***dry***run ***version=1.1.1 ***values=./values.yaml ***values=./genesis.yaml ***values=./values.yml ```

ERROR - ``` failed to download "charts***ose.com/aonity" (hint: running `helm repo update` may help ```

Any suggestions ?? 
temp repo - https://github.com/raj-shekhar1/helm-action-bot

**Comment by raj-shekhar1** [comment]
hey @colinjfw, 
waiting for your suggestions for the resolution and  move ahead with a PR :crossed_fingers:

**Comment by colinjfw** [comment]
@raj-shekhar1 I'd suggest opening a pull request with the forked repository, then we can discuss with a code diff which will help me understand the changes :)

**Comment by raj-shekhar1** [comment]
sure @colinjfw

**Comment by scarby** [comment]
@colinjfw i work with @raj-shekhar1 and have opened a PR: #23  to add a repo parameter (also to specify chart version - which did not seem to be happening). It needs some further testing (and tests written to handle these scenarios - i am not there yet)

I am however opening this for your review :)
