### ISSUE TITLE
deliverybot/helm@v1.6.0 breaks CI

### ISSUE THREAD

**Issue by DavidRouyer** [deliverybot/helm#30]
Hi, I guess the latest version you just pushed break things.

I'm getting the following error now:

```shell
Download action repository 'deliverybot/helm@v1'
##[error]/home/runner/work/_actions/deliverybot/helm/v1/action.yml:
##[error]/home/runner/work/_actions/deliverybot/helm/v1/action.yml: (Line: 20, Col: 48, Idx: 673) - (Line: 20, Col: 48, Idx: 673): Mapping values are not allowed in this context.
##[error]System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
##[error]Fail to load /home/runner/work/_actions/deliverybot/helm/v1/action.yml
```

I'm using `deliverybot/helm@v1` and it worked 5 hours ago

**Comment by benc-uk** [comment]
There's a colon here on this line
https://github.com/deliverybot/helm/blob/7684cf6243992b36f6987dd71252c61a2fd7c7d7/action.yml#L20

Which breaks the YAML and breaks this action, an easy one character fix

**Comment by colinjfw** [comment]
Good eyes, I’ll push a fix.

**Comment by colinjfw** [comment]
`v1.6.1` is released with the fix let me know if you still have any issues https://github.com/deliverybot/helm/commit/1f0d808b77f835b1547c80cdd5080a217465cefe

**Comment by DavidRouyer** [comment]
It works now, thank you!
