### ISSUE TITLE
Allow Kubernetes token (Service account) deployments

### ISSUE THREAD

**Issue by italolelis** [deliverybot/helm#5]
Hello 👋,

First of all, thank you for developing this great Github Action. It will really help in building our deployment flows.

I was wondering if it would be possible to support deploying help via providing a `kubernetes token`, which normally comes from a service account with limited deployment permissions.
In Drone CI for instance, I normally deploy my code like this:

```
- name: deploy
  image: quay.io/ipedrazas/drone-helm
  settings:
    chart: ./charts/my-srv
    client_only: true
    debug: true
    release: my-srv
    skip_tls_verify: true
    values: "tag=${DRONE_TAG}"
    values_files:
    - charts/my-srv/values.yaml
    wait: true
  environment:
    API_SERVER:
      from_secret: kube_server
    KUBERNETES_TOKEN:
      from_secret: kubernetes_token
```

This is a quite powerful way to deploy into kubernetes, without needing to provide a certificate and your kubeconfig file.

Please let me know if this makes sense and if it's possible to implement this. I would be glad to help if I can.

Thank you!!

**Comment by colinjfw** [comment]
Thanks @italolelis! You are definitely right using a service account is the way to go for deploying with Helm. However ultimately we do need a Kubeconfig to coordinate talking to the Kubernetes cluster. I think the question here is how that Kubeconfig file is built up, is that correct?

The way that I've actually built up a Kubeconfig file before is using a script like this: https://gist.github.com/ericchiang/d2a838ddad3f44436ae001a342e1001e. This will embed your service account token and configuration into a Kubeconfig file. If you run that on your machine it should spit out a Kubeconfig file which you can then add into your GitHub repository secrets. 

I noticed that you also have the setting `skip_tls_verify: true` above -- this method will copy in the necessary certificates so you won't have to specify this option!

**Comment by italolelis** [comment]
Hey @colinjfw,

Thanks for your reply. Yeah, that makes sense. I'll try that out and see how everything blends into the workflow. Should be straight forward. Thank you for providing the script, it was really helpful.

I think we can close this issue then
