### ISSUE TITLE
Error when listening on deployment event

### ISSUE THREAD

**Issue by italolelis** [deliverybot/helm#6]
Hello Again,

Now I've bumped into an interesting error that seems to happen only when listening on the `deployment` event. I believe this is an error from GitHub Actions, but I wanted to leave an issue here in case someone has found a way around this.

```
### ERRORED 19:14:52Z

- There was an unexpected error when executing this Action. For help debugging what went wrong, please contact support@github.com. The unique ID for this error is E3D5:63A1:1D1C2:450F0:5D83D3AA
```

Thank you!

**Comment by colinjfw** [comment]
@italolelis I also hit this - I reached out to GitHub support about this but haven't heard back. I don't think it's an issue with any of the workflow syntax because I tried the same syntax on a `push` event and everything looked fine.

I'll let you know if I hear anything.

**Comment by italolelis** [comment]
Ah, I knew there was something going on with GitHub, I also tried on a `push` and there was no sintax error. 

Cool, I appreciate the help!

**Comment by colinjfw** [comment]
I believe that at least for my account GitHub has resolved this issue 🎉
